### ISSUE TITLE
Improve command line usability

### ISSUE THREAD

**Issue by seancorfield** [slipset/deps-deploy#1]
Having to type EDN at the command-line is a bit of a pain. How about having an alternative way to invoke `-main` that accepts three plain string arguments `path/to/my.jar group-id/artifact-id x.y.z`?

**Comment by seancorfield** [comment]
BTW, thanks for this tool -- it gets rid of the one last thing I currently still use Maven for!

**Comment by slipset** [comment]
Thanks for the feedback. During a good nights sleep, I was wondering if it would make sense to just parse the `pom.xml` instead?
Most of this information is available in the pom, at least `group-id/artifact-id` and `version`?

I guess a main like 
`(defn -main ([install-or-deploy artifact name version] ...) ([install-or-deploy artifact] ...))` could be a solution to this?

**Comment by seancorfield** [comment]
My current `clj`-based workflow upload is:
```
mvn deploy:deploy-file -Dfile=${1}.jar -DpomFile=pom.xml -DrepositoryId=clojars -Durl=https://clojars.org/repo/
```
So `mvn` pulls the version and group/artifact IDs from `pom.xml` which is convenient insofar as I don't have to additionally specify them when uploading -- however, the only reason I create a `pom.xml` file in the first place is to provide a) version and group/artifact information for Maven and b) SCM and license information for Clojars itself.

The later has value -- and I'm not sure where `deps-deploy` would get that from otherwise?
