### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by jiyinyiyong** [slipset/deps-deploy#12]
Installed and got the error. Do we need to upgrade? https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder

**Comment by slipset** [comment]
PR welcome

**Comment by jiyinyiyong** [comment]
`slf4j` is not used directly in this package. Only thing I can find is:

https://github.com/clj-commons/pomegranate/blob/a526bc6a3cd113a537725295184af61995941b03/deps.edn#L22

doesn't make sense...

**Comment by cch1** [comment]
Easy solution is to add an SLF4J-supported backend.  I do this:

```
{:main-opts ["-m" "deps-deploy.deps-deploy" "deploy" "janus.jar" true]
  :replace-deps {slipset/deps-deploy {:mvn/version "RELEASE"}
                            org.slf4j/slf4j-nop {:mvn/version "RELEASE"}}}
```
