### ISSUE TITLE
Add support for signing jars

### ISSUE THREAD

**Issue by SevereOverfl0w** [slipset/deps-deploy#3]
Boot's jar task supports `--gpg-sign` & family to provide signing of jars before uploading.  This is an important feature: https://malcolmsparks.com/posts/library-distribution.html .

I can't find any technical details for this, but copying lein/boot's source is a good place to start.

I believe it is worth making a default you turn off.

**Comment by arichiardi** [comment]
Agree this is a good thing to do, `lein` has it configurable as well.
