### ISSUE TITLE
Track releases in GitHub

### ISSUE THREAD

**Issue by cap10morgan** [slipset/deps-deploy#31]
Would be great to have release tags in GitHub that correspond to release versions. I recently was tracking down the source of an error I was seeing, and the line numbers didn't match up w/ the latest unreleased code. I had to track down the git SHA of the latest release from Clojars and then switch to that. If the release had been in GitHub, I could have gone straight to that.

**Comment by opqdonut** [comment]
Same here! Would've samed me some time.

**Comment by slipset** [comment]
I believe the latest version is tagged. Will continue doing so
