### ISSUE TITLE
Release new version w/ alias lookup support

### ISSUE THREAD

**Issue by cap10morgan** [slipset/deps-deploy#32]
I ran into the lack of b4359c5d67ca002d9ed0c4b41b710d7e5a82e3bf in the latest version released to Clojars. I switched to pulling in deps-deploy via git, but it would be great to have this in a released version. Thanks!

**Comment by opqdonut** [comment]
Same here! Could you make a release please?

**Comment by slipset** [comment]
There is now a 0.2.0 release
