### ISSUE TITLE
Remove the need to specify jar file

### ISSUE THREAD

**Issue by jeluard** [slipset/deps-deploy#5]
Leverage the data read from the pom file to locate the Jar file. Current solution is a bit fragile as it requires specifying the same info (like version) twice.

**Comment by jeluard** [comment]
So I don't have to specify the `"path/to/my.jar"` argument? How would that work?

**Comment by slipset** [comment]
No, you still have to specify the path to the jar, because I can’t see where that info is stored in the pom.xml? 

Is there anything I’ve misunderstood/not seen?

**Comment by jeluard** [comment]
I can see build/directory, and packaging, looks like the rest is already known?

**Comment by seancorfield** [comment]
I don't think you can rely on those parts of `pom.xml` to find the specific, named JAR file that should be deployed. You certainly can't rely on them in the general case -- and I'm not convinced there is a sane default for most POM files: look at what `clojure -Spom` generates and the build/directory is `src` (not helpful) and there's no "packaging" information there.

In a Leiningen world, sure, `lein pom jar` produces what you suggest but `lein` already knows how to deploy so `deps-deploy` isn't relevant.
