### ISSUE TITLE
GPG passphrase asked in unexpected moment

### ISSUE THREAD

**Issue by arichiardi** [slipset/deps-deploy#8]
Hi @slipset!

It looks like the signature generation is too aggressive :smile: 

```shell
$ clojure -A:deploy -m deps-deploy.deps-deploy -h
Checking out: https://github.com/slipset/deps-deploy.git at 6f872abc0e1e82f037519e15ddd71eb0ea2759b6
Downloading: com/cemerick/pomegranate/maven-metadata.xml from https://repo1.maven.org/maven2/

gpg passphrase:
```

Maybe just a small tweak, I will try to have a look as well.

Thank you for the package if I haven't thanked you already!

**Comment by slipset** [comment]
I'm having a slow period, so I need some more info here :)
Could you share your `:deploy` alias?

**Comment by arichiardi** [comment]
I am going to close this, because it seems like it disappeared, I cannot reproduce it anymore
